[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#3b4279'

[colors.cursor]
text = '#131318'
cursor = '#bcc3ff'

[colors.normal]
black   = '#131318'
red     = '#e44e44'
green   = '#6ed670'
yellow  = '#dbd57b'
blue    = '#7278e2'
magenta = '#979bbf'
cyan    = '#bcc3ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0635f'
green   = '#86e087'
yellow  = '#e8e297'
blue    = '#c9d0ff'
magenta = '#6176bc'
cyan    = '#7670bd'
white   = '#ffffff'
